// flow-typed signature: cd1ad6de9bfb8e346f49110640e77a25
// flow-typed version: <<STUB>>/bristol_v^0.4.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bristol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bristol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bristol/src/Bristol' {
  declare module.exports: any;
}

declare module 'bristol/src/formatters/commonInfoModel' {
  declare module.exports: any;
}

declare module 'bristol/src/formatters/human' {
  declare module.exports: any;
}

declare module 'bristol/src/formatters/json' {
  declare module.exports: any;
}

declare module 'bristol/src/formatters/syslog' {
  declare module.exports: any;
}

declare module 'bristol/src/logUtil' {
  declare module.exports: any;
}

declare module 'bristol/src/targets/console' {
  declare module.exports: any;
}

declare module 'bristol/src/targets/file' {
  declare module.exports: any;
}

declare module 'bristol/src/targets/loggly' {
  declare module.exports: any;
}

declare module 'bristol/test/setup' {
  declare module.exports: any;
}

declare module 'bristol/test/src/Bristol' {
  declare module.exports: any;
}

declare module 'bristol/test/src/formatters/commonInfoModel' {
  declare module.exports: any;
}

declare module 'bristol/test/src/formatters/human' {
  declare module.exports: any;
}

declare module 'bristol/test/src/formatters/json' {
  declare module.exports: any;
}

declare module 'bristol/test/src/formatters/syslog' {
  declare module.exports: any;
}

declare module 'bristol/test/src/logUtil' {
  declare module.exports: any;
}

declare module 'bristol/test/src/targets/console' {
  declare module.exports: any;
}

declare module 'bristol/test/src/targets/file' {
  declare module.exports: any;
}

declare module 'bristol/test/src/targets/loggly' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bristol/src/Bristol.js' {
  declare module.exports: $Exports<'bristol/src/Bristol'>;
}
declare module 'bristol/src/formatters/commonInfoModel.js' {
  declare module.exports: $Exports<'bristol/src/formatters/commonInfoModel'>;
}
declare module 'bristol/src/formatters/human.js' {
  declare module.exports: $Exports<'bristol/src/formatters/human'>;
}
declare module 'bristol/src/formatters/json.js' {
  declare module.exports: $Exports<'bristol/src/formatters/json'>;
}
declare module 'bristol/src/formatters/syslog.js' {
  declare module.exports: $Exports<'bristol/src/formatters/syslog'>;
}
declare module 'bristol/src/logUtil.js' {
  declare module.exports: $Exports<'bristol/src/logUtil'>;
}
declare module 'bristol/src/targets/console.js' {
  declare module.exports: $Exports<'bristol/src/targets/console'>;
}
declare module 'bristol/src/targets/file.js' {
  declare module.exports: $Exports<'bristol/src/targets/file'>;
}
declare module 'bristol/src/targets/loggly.js' {
  declare module.exports: $Exports<'bristol/src/targets/loggly'>;
}
declare module 'bristol/test/setup.js' {
  declare module.exports: $Exports<'bristol/test/setup'>;
}
declare module 'bristol/test/src/Bristol.js' {
  declare module.exports: $Exports<'bristol/test/src/Bristol'>;
}
declare module 'bristol/test/src/formatters/commonInfoModel.js' {
  declare module.exports: $Exports<'bristol/test/src/formatters/commonInfoModel'>;
}
declare module 'bristol/test/src/formatters/human.js' {
  declare module.exports: $Exports<'bristol/test/src/formatters/human'>;
}
declare module 'bristol/test/src/formatters/json.js' {
  declare module.exports: $Exports<'bristol/test/src/formatters/json'>;
}
declare module 'bristol/test/src/formatters/syslog.js' {
  declare module.exports: $Exports<'bristol/test/src/formatters/syslog'>;
}
declare module 'bristol/test/src/logUtil.js' {
  declare module.exports: $Exports<'bristol/test/src/logUtil'>;
}
declare module 'bristol/test/src/targets/console.js' {
  declare module.exports: $Exports<'bristol/test/src/targets/console'>;
}
declare module 'bristol/test/src/targets/file.js' {
  declare module.exports: $Exports<'bristol/test/src/targets/file'>;
}
declare module 'bristol/test/src/targets/loggly.js' {
  declare module.exports: $Exports<'bristol/test/src/targets/loggly'>;
}
