// flow-typed signature: 7452cf1777370c910a19bfbbe6f9e6e0
// flow-typed version: <<STUB>>/fejl_v^1.0.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fejl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fejl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fejl/lib/http' {
  declare module.exports: any;
}

declare module 'fejl/lib/index' {
  declare module.exports: any;
}

declare module 'fejl/lib/make-error-class' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fejl/lib/http.js' {
  declare module.exports: $Exports<'fejl/lib/http'>;
}
declare module 'fejl/lib/index.js' {
  declare module.exports: $Exports<'fejl/lib/index'>;
}
declare module 'fejl/lib/make-error-class.js' {
  declare module.exports: $Exports<'fejl/lib/make-error-class'>;
}
