// flow-typed signature: 3d58656e45b8534397e9cb251654e4fc
// flow-typed version: <<STUB>>/koa-respond_v^2.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-respond'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-respond' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-respond/lib/koa-respond' {
  declare module.exports: any;
}

declare module 'koa-respond/lib/respond' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-respond/lib/koa-respond.js' {
  declare module.exports: $Exports<'koa-respond/lib/koa-respond'>;
}
declare module 'koa-respond/lib/respond.js' {
  declare module.exports: $Exports<'koa-respond/lib/respond'>;
}
