// flow-typed signature: d7591294d0f339a0628a395280902f1f
// flow-typed version: <<STUB>>/palin_v^2.2.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'palin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'palin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'palin/palin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'palin/palin.js' {
  declare module.exports: $Exports<'palin/palin'>;
}
