// flow-typed signature: 19661e68ba9a96101ed6705eb87d46f5
// flow-typed version: <<STUB>>/smid_v^0.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smid/lib/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'smid/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smid/lib/__tests__/index.test.js' {
  declare module.exports: $Exports<'smid/lib/__tests__/index.test'>;
}
declare module 'smid/lib/index.js' {
  declare module.exports: $Exports<'smid/lib/index'>;
}
